hello_tuple=(1,2,3,4,5)
print(hello_tuple)
print(hello_tuple[2])
print(hello_tuple[1:3])

new_tuple=((1,2,3),(4,5,6))
print(new_tuple)
mixed_tuple=hello_tuple+new_tuple
print(mixed_tuple)
print(hello_tuple.count(3))
print(hello_tuple.index(3))
packed_tuple=1,"Hello",3.14;
print(packed_tuple)
a,b,c=packed_tuple
print(a)
print(b)
print(c)
lst=[1,2,3,4,5]
print(lst)
print(type(lst))
print(type(tuple(lst)))
